#header
name: Stepchen
description: simple & clean
favicon: /fav.png
ga: ''

#nav
nav:
    HOME: /
    ARCHIVE: /archives/
    ABOUT: /about/
    RSS: /atom.xml

#post
excerpt_link: Read More


#about me
aboutMeImg: /about_me.jpg

#sidebar social links
email: chenjiawei100@outlook.com
douban: https://www.douban.com/people/cjw1025/
weibo: https://weibo.com/u/1683654684

#copyright
themeLink: ''

#assets version for cache busting (bump when css/js changed)
asset_version: 41
